repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^(src|tests)/.*\.py$
      - id: ruff-format
        files: ^(src|tests)/.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=5120"]
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: detect-private-key
