[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "W", "UP"]

[tool.ruff.lint.isort]
known-first-party = ["ctrl_alt_heal"]
combine-as-imports = true

[tool.mypy]
python_version = "3.11"
strict = true
warn_unused_ignores = true
disallow_untyped_defs = true
exclude = ["^docs/", "^tests/fixtures/"]

