name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy

      - name: Ruff format check
        run: ruff format --check .

      - name: Ruff lint
        run: ruff check .

      - name: Type check (mypy)
        run: mypy --install-types --non-interactive .
